/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentProviderConfig } from './agentProviderConfig';
import { GameGroup } from './gameGroup';
import { RateInfo } from './rateInfo';


export interface AgentRateInfo { 
    agentId?: number;
    namespace?: string;
    rateInfo?: RateInfo;
    gameGroups?: { [key: string]: GameGroup; };
    groupRateInfo?: { [key: string]: RateInfo; };
    group2providers?: { [key: string]: Array<string>; };
    providerConfigs?: { [key: string]: Array<AgentProviderConfig>; };
    canEdit?: boolean;
    agentLevel?: number;
}

