/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentRateInfo } from './agentRateInfo';


export interface AgentTreeNodeAllOf { 
    rate?: number;
    certificateSN?: string;
    walletNumber?: string;
    blocked?: boolean;
    dealer?: boolean;
    subAgentsCnt?: number;
    nonDeletedSubAgentsCnt?: number;
    agentRateInfo?: AgentRateInfo;
    _c?: string;
}

