/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameGroup { 
    groupId?: number;
    groupName?: string;
    revenueExclude?: boolean;
    colorIndex?: number;
    blocked?: boolean;
    parentId?: number;
    service?: boolean;
    costRate?: number;
    minSaleRate?: number;
    namespace?: string;
}

