/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KioskTreeNodeAllOf { 
    kioskType?: number;
    latitude?: number;
    longitude?: number;
    coordinateType?: number;
    roomId?: number;
    roomName?: string;
    agentId?: number;
    agentName?: string;
    coodinateTs?: number;
    _c?: string;
}

