/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationText } from './notificationText';
import { NotificationAssignment } from './notificationAssignment';


export interface Notification { 
    id?: number;
    name?: string;
    textJson?: string;
    active?: boolean;
    showAtLogin?: boolean;
    startShowAt?: number;
    stopShowAt?: number;
    createdAt?: number;
    createdBy?: number;
    updatedAt?: number;
    updatedBy?: number;
    viewCount?: number;
    viewTimeoutSeconds?: number;
    language2Text?: { [key: string]: NotificationText; };
    assignments?: Array<NotificationAssignment>;
}

