/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RoomTreeNodeAllOf { 
    kioskCnt?: number;
    pcCnt?: number;
    usbCnt?: number;
    rechargerCnt?: number;
    phoneUserCnt?: number;
    _c?: string;
}

