/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AclPermission } from './aclPermission';
import { BasicTreeNode } from './basicTreeNode';
import { RoomTreeNodeAllOf } from './roomTreeNodeAllOf';


export interface RoomTreeNode extends BasicTreeNode, RoomTreeNodeAllOf { 
}

