/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoomInfoAllOf } from './roomInfoAllOf';
import { AclPermission } from './aclPermission';
import { RoomTreeNode } from './roomTreeNode';
import { BasicTreeNode } from './basicTreeNode';


export interface RoomInfo extends RoomTreeNode { 
    agentId?: number;
    panicMode?: boolean;
    notificationPhone?: string;
    watchdogSn?: string;
    address?: string;
    city?: string;
    province?: string;
    country?: string;
    postalCode?: string;
    panicModeToken?: string;
    cashierLogin?: string;
    observerLogin?: string;
    observerEmail?: string;
}

