/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Schedule } from './schedule';


export interface TournamentScheduleEntry { 
    id?: number;
    tournamentId?: number;
    startTime?: number;
    endTime?: number;
    cronSchedule?: string;
    basePrize?: number;
    betRate?: number;
    maxPrize?: number;
    priory?: number;
    days?: number;
    startTimeHour?: number;
    startTimeMinute?: number;
    endTimeHour?: number;
    endTimeMinute?: number;
    schedule?: Schedule;
}

