/**
 * API for mobile admin UI.
 * REST bridge for GWT admin API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TreeNodeType = 'Agent' | 'Room' | 'Kiosk' | 'Tournament' | 'Jackpot';

export const TreeNodeType = {
    Agent: 'Agent' as TreeNodeType,
    Room: 'Room' as TreeNodeType,
    Kiosk: 'Kiosk' as TreeNodeType,
    Tournament: 'Tournament' as TreeNodeType,
    Jackpot: 'Jackpot' as TreeNodeType
};

