FIELD_ACCOUNT_ID: |-
  ID аккаунта

FIELD_USERNAME: |-
  Имя пользователя

FIELD_PASSWORD: |-
  Пароль

FIELD_EMAIL: |-
  Email

FIELD_PHONE: |-
  Номер телефона

FIELD_LANGUAGE: |-
  Язык

FIELD_N_A: |-
  н/д

FIELD_SUBSCRIPTION: |-
  {{appName}} новости и бонусы

FIELD_MY_PROFILE: |-
  Мой профиль

FIELD_LOGOUT: |-
  Выход

FIELD_CONTACTS: |-
  Поддержка

MODAL_TITLE: |-
  Обновление пароля

MODAL_MESSAGE: |-
  Введите текущий пароль, чтобы подтвердить изменения

CONFIRM_PASSWORD: |-
  Подтвердите пароль

CONFIRM_NEW_PASSWORD: |-
  Подтвердите новый пароль

SWITCH_TO_DESKTOP: |-
  Версия для компьютера

MENU: |-
  Меню

PROFILE: |-
  Профиль
