FIELD_ACCOUNT_ID: |-
  Account ID

FIELD_USERNAME: |-
  User name

FIELD_PASSWORD: |-
  Password

FIELD_EMAIL: |-
  Email

FIELD_PHONE: |-
  Phone number

FIELD_LANGUAGE: |-
  Language

FIELD_N_A: |-
  n/a

FIELD_SUBSCRIPTION: |-
  {{appName}} news and bonuses

CONFIRM_PASSWORD: |-
  Confirm Password

CONFIRM_NEW_PASSWORD: |-
  Confirm New Password

FIELD_MY_PROFILE: |-
  My profile

FIELD_LOGOUT: |-
  Logout

FIELD_CONTACTS: |-
  Contact support

MODAL_TITLE: |-
  Password update

MODAL_MESSAGE: |-
  Enter your current password to confirm changes

SWITCH_TO_DESKTOP: |-
  Switch to decktop version
